const level1 = new Level(
    [
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Endboss(),
    ],
    [
        new Cloud('../assets/5_background/layers/4_clouds/1.png', 0, -50),
        new Cloud('../assets/5_background/layers/4_clouds/1.png', 0, 100),
        new Cloud('../assets/5_background/layers/4_clouds/2.png', 200, 400),
        new Cloud('../assets/5_background/layers/4_clouds/1.png', 500, 700),
        new Cloud('../assets/5_background/layers/4_clouds/2.png', 800, 1000),
        new Cloud('../assets/5_background/layers/4_clouds/1.png', 1100, 1300),
        new Cloud('../assets/5_background/layers/4_clouds/2.png', 1400, 1600),
        new Cloud('../assets/5_background/layers/4_clouds/2.png', 1700, 1900),
        new Cloud('../assets/5_background/layers/4_clouds/2.png', 2000, 2200),
        new Cloud('../assets/5_background/layers/4_clouds/2.png', 2300, 2500),
        new Cloud('../assets/5_background/layers/4_clouds/2.png', 2600, 2800),
        new Cloud('../assets/5_background/layers/4_clouds/2.png', 2900, 3100),
        new Cloud('../assets/5_background/layers/4_clouds/2.png', 3200, 3500),
        new Cloud('../assets/5_background/layers/4_clouds/2.png', 3600, 3800),
    ],
    [
        new BackgroundObject('../assets/5_background/layers/air.png', -719),
        new BackgroundObject('../assets/5_background/layers/3_third_layer/2.png', -719),
        new BackgroundObject('../assets/5_background/layers/2_second_layer/2.png', -719),
        new BackgroundObject('../assets/5_background/layers/1_first_layer/2.png', -719),
        new BackgroundObject('../assets/5_background/layers/air.png', 0),
        new BackgroundObject('../assets/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('../assets/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('../assets/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObject('../assets/5_background/layers/air.png', 719),
        new BackgroundObject('../assets/5_background/layers/3_third_layer/2.png', 719),
        new BackgroundObject('../assets/5_background/layers/2_second_layer/2.png', 719),
        new BackgroundObject('../assets/5_background/layers/1_first_layer/2.png', 719),
        new BackgroundObject('../assets/5_background/layers/air.png', 719*2),
        new BackgroundObject('../assets/5_background/layers/3_third_layer/1.png', 719*2),
        new BackgroundObject('../assets/5_background/layers/2_second_layer/1.png', 719*2),
        new BackgroundObject('../assets/5_background/layers/1_first_layer/1.png', 719*2),
        new BackgroundObject('../assets/5_background/layers/air.png', 719*3),
        new BackgroundObject('../assets/5_background/layers/3_third_layer/2.png', 719*3),
        new BackgroundObject('../assets/5_background/layers/2_second_layer/2.png', 719*3),
        new BackgroundObject('../assets/5_background/layers/1_first_layer/2.png', 719*3),
    ]
);