let level1;

function initLevel() {
    level1 = new Level(
        [
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chick(),
            new Chick(),
            new Chick(),
            new Chick(),
            new Chick(),
            new Chick(),
            new Endboss(),
        ],
        [
            new Cloud('../assets/5_background/layers/4_clouds/1.png', 0, -50),
            new Cloud('../assets/5_background/layers/4_clouds/1.png', 0, 100),
            new Cloud('../assets/5_background/layers/4_clouds/2.png', 200, 400),
            new Cloud('../assets/5_background/layers/4_clouds/1.png', 500, 700),
            new Cloud('../assets/5_background/layers/4_clouds/2.png', 800, 1000),
            new Cloud('../assets/5_background/layers/4_clouds/1.png', 1100, 1300),
            new Cloud('../assets/5_background/layers/4_clouds/2.png', 1400, 1600),
            new Cloud('../assets/5_background/layers/4_clouds/2.png', 1700, 1900),
            new Cloud('../assets/5_background/layers/4_clouds/2.png', 2000, 2200),
            new Cloud('../assets/5_background/layers/4_clouds/2.png', 2300, 2500),
            new Cloud('../assets/5_background/layers/4_clouds/2.png', 2600, 2800),
            new Cloud('../assets/5_background/layers/4_clouds/2.png', 2900, 3100),
            new Cloud('../assets/5_background/layers/4_clouds/2.png', 3200, 3500),
            new Cloud('../assets/5_background/layers/4_clouds/2.png', 3600, 3800),
        ],
        [
            new BackgroundObject('../assets/5_background/layers/air.png', -719),
            new BackgroundObject('../assets/5_background/layers/3_third_layer/2.png', -719),
            new BackgroundObject('../assets/5_background/layers/2_second_layer/2.png', -719),
            new BackgroundObject('../assets/5_background/layers/1_first_layer/2.png', -719),
            new BackgroundObject('../assets/5_background/layers/air.png', 0),
            new BackgroundObject('../assets/5_background/layers/3_third_layer/1.png', 0),
            new BackgroundObject('../assets/5_background/layers/2_second_layer/1.png', 0),
            new BackgroundObject('../assets/5_background/layers/1_first_layer/1.png', 0),
            new BackgroundObject('../assets/5_background/layers/air.png', 719),
            new BackgroundObject('../assets/5_background/layers/3_third_layer/2.png', 719),
            new BackgroundObject('../assets/5_background/layers/2_second_layer/2.png', 719),
            new BackgroundObject('../assets/5_background/layers/1_first_layer/2.png', 719),
            new BackgroundObject('../assets/5_background/layers/air.png', 719 * 2),
            new BackgroundObject('../assets/5_background/layers/3_third_layer/1.png', 719 * 2),
            new BackgroundObject('../assets/5_background/layers/2_second_layer/1.png', 719 * 2),
            new BackgroundObject('../assets/5_background/layers/1_first_layer/1.png', 719 * 2),
            new BackgroundObject('../assets/5_background/layers/air.png', 719 * 3),
            new BackgroundObject('../assets/5_background/layers/3_third_layer/2.png', 719 * 3),
            new BackgroundObject('../assets/5_background/layers/2_second_layer/2.png', 719 * 3),
            new BackgroundObject('../assets/5_background/layers/1_first_layer/2.png', 719 * 3),
        ],
        [
            new Bottle('../assets/6_salsa_bottle/1_salsa_bottle_on_ground.png', 300, 500),
            new Bottle('../assets/6_salsa_bottle/1_salsa_bottle_on_ground.png', 600, 900),
            new Bottle('../assets/6_salsa_bottle/2_salsa_bottle_on_ground.png', 800, 1200),
            new Bottle('../assets/6_salsa_bottle/2_salsa_bottle_on_ground.png', 1200, 1500),
            new Bottle('../assets/6_salsa_bottle/1_salsa_bottle_on_ground.png', 1600, 1900),
            new Bottle('../assets/6_salsa_bottle/2_salsa_bottle_on_ground.png', 1700, 1900),
            new Bottle('../assets/6_salsa_bottle/1_salsa_bottle_on_ground.png', 2000, 2200),
            new Bottle('../assets/6_salsa_bottle/2_salsa_bottle_on_ground.png', 2100, 2300),
        ],
        [
            new StatusBar('health'),
            new StatusBar('coins'),
            new StatusBar('bottles'),
            new StatusBar('endboss'),
        ],
        [
            new Coin(600, 900),
            new Coin(800, 1200),
            new Coin(1200, 1500),
            new Coin(1600, 1900),
            new Coin(1700, 1900),
        ]
    );
}